Added Groups API documentation
cfengine/documentation pull request #3052
Opened 2023-06-14 18:34 UTC by aleksandrychev

Ticket: ENT-10196

2023-06-14 18:35 UTC, aleksandrychev commented
@cf-bottom jenkins

2023-06-14 18:35 UTC, aleksandrychev commented
@nickanderson please review

2023-06-14 18:38 UTC, aleksandrychev commented
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=fr-tests&build=6095)](https://ci.cfengine.com/job/fr-tests/6095/)

2023-06-14 18:38 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=fast-build-and-deploy-docs-master&build=364)](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/364/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/364/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-364/output/_site/

2023-06-14 21:02 UTC, nickanderson requested changes

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-14 21:02 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +```
```suggestion
```json
```

2023-06-15 09:00 UTC, aleksandrychev commented on api/enterprise-api-ref/personal-groups.markdown
> +                    "type": "hostkey",
only hostkey for now

2023-06-15 09:00 UTC, aleksandrychev commented on api/enterprise-api-ref/personal-groups.markdown
> +  https://hub.cfengine.com/api/host-groups/personal/ \
fixed

2023-06-15 09:02 UTC, aleksandrychev commented on api/enterprise-api-ref/personal-groups.markdown
> +                "includes": {
you need to wrap all your filters into `filter` property. but hostsFitlers adds it additionally to existing inv or class filters

2023-06-15 10:01 UTC, aleksandrychev commented on api/enterprise-api-ref/personal-groups.markdown
> +**Method:** PATCH
no minimal, just wrap hostsFilter into filter

2023-06-15 12:44 UTC, olehermanse requested changes

2023-06-15 13:13 UTC, aleksandrychev commented on api/enterprise-api-ref/personal-groups.markdown
> +            "hostsFilter": {
added

2023-06-15 15:24 UTC, nickanderson commented on api/enterprise-api-ref/personal-groups.markdown
> +      "filter":{
This filter.filter thing was a bit confusing to me. For whatever reason I wasn't seeing both, making me think that hostsFilter and hostcontextinclude/exclude were outside of filter.

2023-06-15 16:30 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +**URI:** https://hub.cfengine.com/api/host-groups/shared/:id/cmdb/:type/:name/
Is it expected for this trailing slash to be strictly required?

I was struggling with the API for a while until I finally realized I was missing the trailing `/` things worked as soon as I added it.

2023-06-15 16:36 UTC, nickanderson commented on api/enterprise-api-ref/shared-groups.markdown
> +## Delete host's configurations
Delete host's configurations? Or delete /group's/ configurations?

2023-06-15 16:54 UTC, merged