ENT-9083: Updated docs to include new behaviour of package[update]smatching
cfengine/documentation pull request #3065
Opened 2023-06-22 11:58 UTC by larsewi

2023-06-22 12:53 UTC, craigcomstock requested changes

2023-06-22 12:53 UTC, craigcomstock commented on reference/functions/packagesmatching.markdown
> +At no time will both the standard and the legacy data be available to these functions silmontaneously.
```suggestion
At no time will both the standard and the legacy data be available to these functions simultaneously.
```

2023-06-22 12:53 UTC, craigcomstock commented on reference/functions/packageupdatesmatching.markdown
> +At no time will both the standard and the legacy data be available to these functions silmontaneously.
```suggestion
At no time will both the standard and the legacy data be available to these functions simultaneously.
```

2023-06-22 16:50 UTC, nickanderson commented on reference/functions/packagesmatching.markdown
> +However, since the release of CFEngine 3.22, the `packagesmatching` and `packageupdatesmatching` policy functions will look for and use the existing software inventory databases (available in `$(sys.
3.22? Won't this be 3.23?

And then if it's backported, 3.18.6, 3.21.3

2023-06-22 16:50 UTC, nickanderson commented on reference/functions/packageupdatesmatching.markdown
> +At no time will both the standard and the legacy data be available to these functions simultaneously.
Seems like this should be noted in the History section

2023-06-22 16:50 UTC, nickanderson commented on reference/functions/packagesmatching.markdown
> +However, since the release of CFEngine 3.22, the `packagesmatching` and `packageupdatesmatching` policy functions will look for and use the existing software inventory databases (available in `$(sys.
Also seems liek this should be mentioned in the history section.

2023-06-29 13:16 UTC, nickanderson approved these changes

2023-06-29 13:16 UTC, nickanderson commented
@cf-bottom jenkins, please

2023-06-29 13:19 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=fast-build-and-deploy-docs-master&build=376)](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/376/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/376/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-376/output/_site/

2023-06-29 13:34 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=fast-build-and-deploy-docs-master&build=377)](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/377/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/377/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-377/output/_site/

2023-06-29 15:44 UTC, nickanderson commented
@cf-bottom jenkins, please

2023-06-29 17:08 UTC, merged

2023-07-17 15:19 UTC, larsewi commented
Cherry picked to
 - https://github.com/cfengine/documentation/pull/3073
 - https://github.com/cfengine/documentation/pull/3074